import type { PillarConfig, PillarId } from '../../shared/types/pillar.types.js';

const EDUCATE_CONFIG: PillarConfig = {
  id: 'educate',
  name: 'Educate',
  description: 'Teach something valuable your audience can act on',
  icon: 'GraduationCap',
  proportion: 0.30,
  slideRange: { min: 8, max: 12 },
  requiredRoles: ['hook', 'context', 'content', 'cta'],
  optionalRoles: ['tension', 'soft-cta'],
  objective: "Teach something valuable and actionable from the user's area of expertise",
  requiredElements: [
    'Framework, list, or step-by-step from the source',
    'Concrete data points from the source (never invented)',
    'Actionable takeaway the reader can apply immediately',
  ],
  forbiddenElements: [
    'Opinion without supporting data',
    'Gratuitous provocation',
    'Direct selling or product pitch',
  ],
  toneOverride: 'Teacher-mode: calm authority, trusted guide. Explain complex things simply.',
  ctaStyle: 'Save this / Share with someone who needs it / Apply this today',
  captionStyle: 'micro-story',
  queryAngles: ['tutorial', 'framework', 'data', 'trend', 'how-to'],
  sourceWeights: { google_news: 1.5, reddit: 1.0, twitter: 0.8, blog: 1.8 },
  scoringWeights: { recency: 0.20, engagement: 0.15, relevance: 0.25, richness: 0.40 },
  hookAffinityBoost: {
    'specific-number': 1.5,
    'curiosity-mystery': 1.5,
    'direct-controversy': 0.8,
    'polarization': 0.5,
    'transformative-promise': 1.0,
    'social-proof': 0.8,
  },
  productSeedIntensity: 'whisper',
};

const PROVOKE_CONFIG: PillarConfig = {
  id: 'provoke',
  name: 'Provoke',
  description: 'Challenge a belief your audience holds — with proof',
  icon: 'Zap',
  proportion: 0.20,
  slideRange: { min: 4, max: 7 },
  requiredRoles: ['hook', 'context', 'content', 'cta'],
  optionalRoles: ['tension'],
  objective: 'Break a limiting belief using surprising data or counter-narrative',
  requiredElements: [
    'Surprising data point or counter-intuitive fact in the hook',
    'Clear counter-narrative that challenges conventional wisdom',
    'Direct confrontation — no hedging, no both-sides',
  ],
  forbiddenElements: [
    'Hedging language (maybe, perhaps, in my opinion)',
    'Balanced/conciliatory tone',
    'Long explanations — short, punchy slides',
  ],
  toneOverride: "Confrontational: no half-measures, no apologies. Say what others won't.",
  ctaStyle: 'Agree? Comment / Tag someone who needs to hear this',
  captionStyle: 'one-liner',
  queryAngles: ['myth', 'controversy', 'failure', 'unpopular-opinion', 'pain-validation'],
  sourceWeights: { google_news: 0.8, reddit: 1.2, twitter: 1.5, blog: 0.6 },
  scoringWeights: { recency: 0.40, engagement: 0.30, relevance: 0.20, richness: 0.10 },
  hookAffinityBoost: {
    'direct-controversy': 1.5,
    'polarization': 1.5,
    'curiosity-mystery': 1.0,
    'specific-number': 0.8,
    'transformative-promise': 0.5,
    'social-proof': 0.5,
  },
  productSeedIntensity: 'none',
};

const PROVE_CONFIG: PillarConfig = {
  id: 'prove',
  name: 'Prove',
  description: 'Show tangible results with evidence and before/after',
  icon: 'TrendingUp',
  proportion: 0.20,
  slideRange: { min: 6, max: 8 },
  requiredRoles: ['hook', 'context', 'content', 'tension', 'soft-cta', 'cta'],
  optionalRoles: [],
  objective: 'Demonstrate tangible results with documented evidence',
  requiredElements: [
    'Concrete number or metric',
    'Before/after comparison',
    'Documented process (not just result)',
  ],
  forbiddenElements: [
    'Vague promises without data',
    'Results without context',
    'Exaggeration or unverifiable claims',
  ],
  toneOverride: 'Factual: numbers speak. Let the proof sell itself.',
  ctaStyle: 'Want the same? / Link in bio / DM me',
  captionStyle: 'micro-story',
  queryAngles: ['case-study', 'before-after', 'results', 'metrics', 'testimonial'],
  sourceWeights: { google_news: 1.0, reddit: 1.5, twitter: 0.8, blog: 1.5 },
  scoringWeights: { recency: 0.15, engagement: 0.20, relevance: 0.35, richness: 0.30 },
  hookAffinityBoost: {
    'transformative-promise': 1.5,
    'social-proof': 1.5,
    'specific-number': 1.0,
    'direct-controversy': 0.8,
    'curiosity-mystery': 0.8,
    'polarization': 0.5,
  },
  productSeedIntensity: 'mention',
};

const CONNECT_CONFIG: PillarConfig = {
  id: 'connect',
  name: 'Connect',
  description: 'Create emotional identification with your audience',
  icon: 'Heart',
  proportion: 0.20,
  slideRange: { min: 5, max: 8 },
  requiredRoles: ['hook', 'context', 'content', 'soft-cta', 'cta'],
  optionalRoles: ['tension'],
  objective: "Create emotional identification — speak WITH the audience, not AT them",
  requiredElements: [
    'Genuine vulnerability or relatable moment',
    "Audience's own language and expressions",
    "Moment of identification (reader thinks: 'that's me')",
  ],
  forbiddenElements: [
    'Professorial/lecturing tone',
    'Cold data without emotional context',
    'Any selling or product promotion',
  ],
  toneOverride: "Empathetic: speak as a peer who's been there. Warm, honest, real.",
  ctaStyle: 'Relate? Share / Comment your experience / Tag someone',
  captionStyle: 'micro-story',
  queryAngles: ['struggle', 'behind-scenes', 'community-question', 'relatable-moment', 'audience-voice'],
  sourceWeights: { google_news: 0.5, reddit: 1.5, twitter: 1.3, blog: 0.7 },
  scoringWeights: { recency: 0.25, engagement: 0.35, relevance: 0.25, richness: 0.15 },
  hookAffinityBoost: {
    'curiosity-mystery': 1.5,
    'transformative-promise': 1.5,
    'social-proof': 1.0,
    'direct-controversy': 0.5,
    'specific-number': 0.8,
    'polarization': 0.5,
  },
  productSeedIntensity: 'none',
};

const CONVERT_CONFIG: PillarConfig = {
  id: 'convert',
  name: 'Convert',
  description: 'Present your offer as the natural solution',
  icon: 'Target',
  proportion: 0.10,
  slideRange: { min: 8, max: 10 },
  requiredRoles: ['hook', 'context', 'content', 'tension', 'soft-cta', 'cta'],
  optionalRoles: [],
  objective: "Present the user's offer as the natural solution to a documented problem",
  requiredElements: [
    'Problem → solution narrative arc',
    'Social proof or credibility signal',
    'Clear CTA matching offers[].purchase_method',
  ],
  forbiddenElements: [
    'Hard selling without context',
    'Impossible promises',
    'Desperation or urgency manipulation',
  ],
  toneOverride: 'Persuasive: confident, direct, no desperation. The offer speaks for itself.',
  ctaStyle: 'Dynamic — derived from offers[].purchase_method + cta_keyword',
  captionStyle: 'challenge',
  queryAngles: ['comparison', 'cost-analysis', 'competitor-weakness', 'roi-data', 'objection-breaker'],
  sourceWeights: { google_news: 1.3, reddit: 0.8, twitter: 1.2, blog: 1.4 },
  scoringWeights: { recency: 0.30, engagement: 0.20, relevance: 0.30, richness: 0.20 },
  hookAffinityBoost: {
    'direct-controversy': 1.5,
    'specific-number': 1.5,
    'social-proof': 1.0,
    'transformative-promise': 1.0,
    'curiosity-mystery': 0.8,
    'polarization': 0.8,
  },
  productSeedIntensity: 'full',
};

export const PILLAR_CONFIGS: Record<PillarId, PillarConfig> = {
  educate: EDUCATE_CONFIG,
  provoke: PROVOKE_CONFIG,
  prove: PROVE_CONFIG,
  connect: CONNECT_CONFIG,
  convert: CONVERT_CONFIG,
};

export const ALL_PILLAR_IDS: PillarId[] = ['educate', 'provoke', 'prove', 'connect', 'convert'];
