// Pillar suggestions per niche — used in Setup Wizard v2 Step 3
// Each niche maps to ~6–8 suggested content pillars.

export const NICHE_OPTIONS = [
    'Marketing Digital',
    'Vendas',
    'Finanças Pessoais',
    'Investimentos',
    'Saúde & Fitness',
    'Nutrição',
    'Psicologia',
    'Espiritualidade',
    'Empreendedorismo',
    'Gestão de Negócios',
    'RH & Carreira',
    'Educação',
    'Idiomas',
    'Tecnologia',
    'Design',
    'Fotografia',
    'Lifestyle',
    'Moda',
    'Gastronomia',
    'Viagem',
    'Outro',
] as const;

export type Niche = (typeof NICHE_OPTIONS)[number];

export const PILLAR_SUGGESTIONS: Record<string, string[]> = {
    'Marketing Digital': [
        'Estratégia de conteúdo',
        'Tráfego pago',
        'SEO e orgânico',
        'Funil de vendas',
        'Copywriting',
        'Email marketing',
        'Analytics e métricas',
        'Branding digital',
    ],
    Vendas: [
        'Técnicas de fechamento',
        'Objeções e contornos',
        'Prospecção ativa',
        'Rapport e conexão',
        'Follow-up estratégico',
        'Script de vendas',
        'Mentalidade de vendedor',
        'CRM e processos',
    ],
    'Finanças Pessoais': [
        'Orçamento e controle',
        'Reserva de emergência',
        'Sair das dívidas',
        'Educação financeira',
        'Planejamento financeiro',
        'Renda extra',
        'Hábitos de riqueza',
        'Mentalidade financeira',
    ],
    Investimentos: [
        'Renda fixa',
        'Renda variável',
        'Fundos imobiliários',
        'Criptomoedas',
        'Análise de ações',
        'Carteira diversificada',
        'Aposentadoria e FIRE',
        'Educação do investidor',
    ],
    'Saúde & Fitness': [
        'Treinos e exercícios',
        'Perda de peso',
        'Ganho de massa',
        'Mobilidade e flexibilidade',
        'Saúde mental',
        'Hábitos saudáveis',
        'Suplementação',
        'Motivação e disciplina',
    ],
    Nutrição: [
        'Alimentação saudável',
        'Receitas fit',
        'Nutrição esportiva',
        'Reeducação alimentar',
        'Mitos alimentares',
        'Suplementos',
        'Dietas e protocolos',
        'Mindful eating',
    ],
    Psicologia: [
        'Ansiedade e saúde mental',
        'Terapia e autoconhecimento',
        'Relacionamentos',
        'Traumas e cura',
        'Comportamento humano',
        'Inteligência emocional',
        'Comunicação não-violenta',
        'Desenvolvimento pessoal',
    ],
    Espiritualidade: [
        'Meditação',
        'Práticas espirituais',
        'Propósito de vida',
        'Lei da atração',
        'Autoconhecimento',
        'Mindfulness',
        'Cura interior',
        'Ancestralidade',
    ],
    Empreendedorismo: [
        'Mentalidade empreendedora',
        'Validação de negócio',
        'Marketing e vendas',
        'Gestão financeira',
        'Time e cultura',
        'Produtividade',
        'Escalabilidade',
        'Histórias de sucesso e fracasso',
    ],
    'Gestão de Negócios': [
        'Processos e sistemas',
        'Liderança',
        'Gestão de equipes',
        'Indicadores de performance',
        'Cultura organizacional',
        'Tomada de decisão',
        'Gestão financeira empresarial',
        'Inovação',
    ],
    'RH & Carreira': [
        'Desenvolvimento de carreira',
        'Liderança e gestão',
        'Recrutamento e seleção',
        'Cultura e engajamento',
        'Soft skills',
        'Remuneração e benefícios',
        'Diversidade e inclusão',
        'Transição de carreira',
    ],
    Educação: [
        'Metodologias de ensino',
        'Tecnologia na educação',
        'Aprendizagem ativa',
        'Gestão de sala de aula',
        'Educação infantil',
        'EAD e ensino online',
        'Avaliação e feedback',
        'Inclusão educacional',
    ],
    Idiomas: [
        'Inglês para negócios',
        'Dicas de fluência',
        'Vocabulário e gramática',
        'Pronúncia e listening',
        'Métodos de aprendizado',
        'Imersão cultural',
        'Idioma no dia a dia',
        'Erros comuns',
    ],
    Tecnologia: [
        'Programação e dev',
        'Inteligência Artificial',
        'Tendências tech',
        'Carreira em TI',
        'Startups e inovação',
        'Segurança digital',
        'Ferramentas produtividade',
        'Educação tech',
    ],
    Design: [
        'Identidade visual',
        'UI/UX design',
        'Design gráfico',
        'Tipografia',
        'Cores e paletas',
        'Ferramentas de design',
        'Portfólio e carreira',
        'Processo criativo',
    ],
    Fotografia: [
        'Técnica fotográfica',
        'Iluminação',
        'Edição e pós-produção',
        'Fotografia de retrato',
        'Fotografia de produto',
        'Negócio fotográfico',
        'Equipamentos',
        'Estilo e estética',
    ],
    Lifestyle: [
        'Rotina e hábitos',
        'Produtividade pessoal',
        'Bem-estar',
        'Viagem e experiências',
        'Espaços e decoração',
        'Sustentabilidade',
        'Autocuidado',
        'Hobbies e lazer',
    ],
    Moda: [
        'Looks e outfits',
        'Tendências da temporada',
        'Moda sustentável',
        'Personal style',
        'Dicas de styling',
        'Compras inteligentes',
        'Moda plus size',
        'Beleza e make',
    ],
    Gastronomia: [
        'Receitas e técnicas',
        'Culinária do mundo',
        'Harmonização',
        'Confeitaria e panificação',
        'Restaurantes e viagens',
        'Alimentação saudável',
        'Chef em casa',
        'Negócio gastronômico',
    ],
    Viagem: [
        'Destinos nacionais',
        'Destinos internacionais',
        'Dicas de economia',
        'Viagem solo',
        'Viagem em família',
        'Roteiros prontos',
        'Hospedagem e transporte',
        'Cultura e gastronomia local',
    ],
    Outro: [
        'Educação e conhecimento',
        'Entretenimento',
        'Comunidade e conexão',
        'Bastidores',
        'Cases e histórias',
        'Dicas práticas',
        'Tendências',
        'Opinião e análise',
    ],
};
