-- Migration: Add content_json column to sf_posts table
-- This column stores the original content-only JSON generated by GPT
-- before theme application. This allows theme switching in the web dashboard.

-- Add content_json column (nullable for backward compatibility with existing posts)
ALTER TABLE sf_posts
ADD COLUMN IF NOT EXISTS content_json jsonb DEFAULT NULL;

-- Create index for faster queries on content_json (optional, for future filtering)
-- CREATE INDEX IF NOT EXISTS idx_sf_posts_content_json ON sf_posts USING GIN (content_json);
