import { PillarTemplate } from '../forge-shadowfeed.types.js';

export const brandBreakdownTemplates: PillarTemplate[] = [
  {
    id: 'bb-001',
    theme: 'Nike content strategy dissected',
    hookLine: 'Nike doesn\'t sell shoes on Instagram. They sell identity. Here\'s the exact content formula they use — and how you can adapt it.',
    bodyHints: [
      'Break down Nike\'s content pillar distribution',
      'Analyze their hook patterns and visual consistency',
      'Show the ratio of aspirational vs product content',
      'Extract 3 replicable tactics for any small brand',
    ],
    variables: [],
    toneIntensity: 'high',
    slideRange: { min: 10, max: 14 },
  },
  {
    id: 'bb-002',
    theme: 'How {brand} built authority through content',
    hookLine: '{brand} went from {X} to {Y} followers in {Z} months. It wasn\'t luck. It was a documented content machine.',
    bodyHints: [
      'Analyze the brand\'s posting frequency and consistency',
      'Break down their content format mix (reels, carousels, stories)',
      'Identify the core message repeated across all content',
      'Extract the growth formula others can replicate',
    ],
    variables: ['brand', 'X', 'Y', 'Z'],
    toneIntensity: 'high',
    slideRange: { min: 10, max: 14 },
  },
  {
    id: 'bb-003',
    theme: 'The Duolingo social media playbook',
    hookLine: 'Duolingo\'s TikTok has {X}M followers. Their secret? They broke every corporate social media rule. Systematically.',
    bodyHints: [
      'Analyze what rules Duolingo breaks and why it works',
      'Show the contrast with traditional corporate social media',
      'Break down their content formula: character + chaos + consistency',
      'Identify what small brands can and cannot replicate from this approach',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 10, max: 14 },
  },
  {
    id: 'bb-004',
    theme: 'Why luxury brands post less but earn more engagement',
    hookLine: 'Chanel posts {X} times per week. A typical small business posts {Y}. Chanel gets {Z}x the engagement. Here\'s why less is more — for them.',
    bodyHints: [
      'Analyze luxury brand posting frequency strategy',
      'Show the scarcity principle applied to content',
      'Explain why this works for established brands but not for growing ones',
      'Present the frequency strategy that actually works for growing brands',
    ],
    variables: ['X', 'Y', 'Z'],
    toneIntensity: 'medium',
    slideRange: { min: 10, max: 12 },
  },
  {
    id: 'bb-005',
    theme: 'Personal brand vs corporate brand strategy',
    hookLine: 'Corporate brands sell products. Personal brands sell trust. The content strategy is completely different. Here\'s how.',
    bodyHints: [
      'Map the key differences in content approach',
      'Show examples of personal brands that outperform corporate ones',
      'Break down the trust-building content formula',
      'Present the hybrid model that works for solopreneurs',
    ],
    variables: [],
    toneIntensity: 'high',
    slideRange: { min: 10, max: 14 },
  },
  {
    id: 'bb-006',
    theme: 'The content formula behind {niche} market leaders',
    hookLine: 'The top {X} brands in {niche} share one content pattern. They all use the same pillar distribution. Here it is.',
    bodyHints: [
      'Present the common content pattern across market leaders',
      'Show the pillar distribution with percentages',
      'Analyze the hook types that dominate the niche',
      'Give the adapted formula for smaller players in the same niche',
    ],
    variables: ['X', 'niche'],
    toneIntensity: 'high',
    slideRange: { min: 10, max: 14 },
  },
  {
    id: 'bb-007',
    theme: 'How subscription brands use content to reduce churn',
    hookLine: 'Subscription brands that post {X}+ times per week have {Y}% lower churn. Content isn\'t marketing for them — it\'s retention.',
    bodyHints: [
      'Show the correlation between content frequency and churn rates',
      'Analyze the content types that drive retention (educational, community)',
      'Break down the post-purchase content funnel',
      'Present the minimum content cadence for retention impact',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'medium',
    slideRange: { min: 10, max: 14 },
  },
  {
    id: 'bb-008',
    theme: 'Brand voice consistency analysis',
    hookLine: 'Great brands sound the same in every post. Not because they\'re boring — because they\'re engineered. Here\'s how {brand} does it.',
    bodyHints: [
      'Analyze the brand\'s voice consistency across 50+ posts',
      'Identify the vocabulary, tone markers, and sentence structures repeated',
      'Show how consistency creates recognition and trust',
      'Present a voice engineering framework for any brand',
    ],
    variables: ['brand'],
    toneIntensity: 'medium',
    slideRange: { min: 10, max: 12 },
  },
  {
    id: 'bb-009',
    theme: 'The rebranding content strategy playbook',
    hookLine: '{brand} rebranded and lost {X}% of engagement in 2 weeks. Then they recovered in {Y} days. The content pivot they made was surgical.',
    bodyHints: [
      'Analyze the pre-rebrand content vs post-rebrand',
      'Show the engagement dip and recovery timeline',
      'Break down the content strategy that drove recovery',
      'Extract lessons for any brand considering a pivot',
    ],
    variables: ['brand', 'X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 10, max: 14 },
  },
  {
    id: 'bb-010',
    theme: 'How brands use controversy strategically',
    hookLine: 'The most engaging brand content is controversial. But there\'s a formula to controversy that doesn\'t backfire. {brand} mastered it.',
    bodyHints: [
      'Analyze how the brand uses controversy without brand damage',
      'Show the types of controversy that drive engagement vs backlash',
      'Present the "safe controversy" framework',
      'Give examples of controversial posts that built authority',
    ],
    variables: ['brand'],
    toneIntensity: 'high',
    slideRange: { min: 10, max: 14 },
  },
];
