import { PillarTemplate } from '../forge-shadowfeed.types.js';

export const educationalValueTemplates: PillarTemplate[] = [
  {
    id: 'edu-001',
    theme: 'How the Instagram algorithm actually works',
    hookLine: 'The Instagram algorithm doesn\'t read your content. It reads how people react to it. Crucial difference.',
    bodyHints: [
      'Explain the signals the algorithm prioritizes (screen time, saves, shares)',
      'Debunk the myth that visual quality is the primary factor',
      'Show how posting consistency affects distribution',
      'Present what you can control vs what you cannot',
    ],
    variables: [],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 12 },
  },
  {
    id: 'edu-002',
    theme: 'Why consistency beats creativity',
    hookLine: '{X} mediocre posts published consistently outperform {Y} excellent posts published sporadically. Every time.',
    bodyHints: [
      'Present growth data of consistent vs sporadic accounts',
      'Explain the compound effect of constant presence',
      'Show how the algorithm penalizes irregularity',
      'Conclude: system > talent in the long game',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'edu-003',
    theme: 'The anatomy of a carousel that converts',
    hookLine: 'A carousel that converts has structure. Not inspiration. Learn the structure and the result becomes repeatable.',
    bodyHints: [
      'Present the slide-by-slide structure (hook, problem, escalation, solution, proof, CTA)',
      'Show what each slide must accomplish for the reader',
      'Reveal the most common structural mistakes',
      'Conclude with a replicable template',
    ],
    variables: [],
    toneIntensity: 'medium',
    slideRange: { min: 10, max: 12 },
  },
  {
    id: 'edu-004',
    theme: 'The first words determine everything',
    hookLine: 'You have {X} words to capture attention before the "see more" link. How many are you wasting being polite?',
    bodyHints: [
      'Show how the feed is scanned, not read',
      'Present hook patterns that work on Instagram',
      'Analyze weak vs strong hooks with real examples',
      'Give a replicable hook structure in 3 formats',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'edu-005',
    theme: 'The content pillar system explained',
    hookLine: 'Stop inventing what to post every day. The pillar system is the only method that works without depending on inspiration.',
    bodyHints: [
      'Define what a content pillar is in practice',
      'Show how to define pillars for any niche',
      'Present how to rotate pillars in sequence without repetition',
      'Conclude: pillars + calendar = predictability',
    ],
    variables: [],
    toneIntensity: 'medium',
    slideRange: { min: 8, max: 12 },
  },
  {
    id: 'edu-006',
    theme: 'Posting timing data that matters',
    hookLine: 'Posting at the wrong time can reduce your reach by up to {X}%. And the "right time" changes by niche, not by trend.',
    bodyHints: [
      'Show how to identify the best time for your specific audience',
      'Present the metrics that reveal your audience peak hours',
      'Destroy the myth of universal posting schedules',
      'Give a 2-week timing test method',
    ],
    variables: ['X'],
    toneIntensity: 'medium',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'edu-007',
    theme: 'How to create hooks that hold in carousels',
    hookLine: 'The carousel cover doesn\'t sell the product. It sells the next slide. Understanding this changes everything.',
    bodyHints: [
      'Explain each slide\'s function relative to the next',
      'Show cover patterns that generate high CTR',
      'Present the psychology of curiosity applied to carousels',
      'Give {X} tested cover formats with real results',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 12 },
  },
  {
    id: 'edu-008',
    theme: 'The authenticity paradox on Instagram',
    hookLine: 'Authenticity is perception, not process. You can have an automated system and still appear completely authentic.',
    bodyHints: [
      'Differentiate brand voice from production method',
      'Show that audiences don\'t care how content was made',
      'Present how to calibrate the system for the right voice',
      'Conclude: authenticity is about what you say, not how you produce',
    ],
    variables: [],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'edu-009',
    theme: 'Why most carousels fail',
    hookLine: '{X}% of carousels lose the reader by the third slide. It\'s not because the content is bad. It\'s because the structure is.',
    bodyHints: [
      'Identify the most common mistakes that make readers drop carousels',
      'Show how each mistake can be fixed with structural adjustments',
      'Present before-and-after optimization examples',
      'Conclude with a retention checklist for carousels',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 12 },
  },
  {
    id: 'edu-010',
    theme: 'Post structure for authority building',
    hookLine: 'Authority on Instagram isn\'t ego. It\'s repeated structure of proof. Learn the structure and apply it nonstop.',
    bodyHints: [
      'Define what builds real authority (data, cases, methodology)',
      'Present the authority post structure slide by slide',
      'Show how planned repetition creates perception of expertise',
      'Conclude with recommended authority post frequency per pillar',
    ],
    variables: [],
    toneIntensity: 'medium',
    slideRange: { min: 8, max: 12 },
  },
  {
    id: 'edu-011',
    theme: 'Hashtags: what actually works today',
    hookLine: 'Hashtags don\'t make you grow more. They make you grow differently. And {X}% of professionals use them wrong.',
    bodyHints: [
      'Demystify the role of hashtags in current organic reach',
      'Present the correct hashtag mix strategy by size',
      'Show what replaced hashtags as the main reach factor',
      'Give a hashtag selection framework by objective',
    ],
    variables: ['X'],
    toneIntensity: 'medium',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'edu-012',
    theme: 'The science of scroll-stopping content',
    hookLine: 'The average user scrolls {X} meters of feed per day. Your content has 0.3 seconds to earn a pause. Here\'s the science behind it.',
    bodyHints: [
      'Present data on scroll behavior and attention spans',
      'Explain visual and textual triggers that cause pauses',
      'Show the pattern behind top-performing carousel covers',
      'Give actionable design principles for scroll-stopping content',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 12 },
  },
];
