import { PillarTemplate } from '../forge-shadowfeed.types.js';

export const proofOfMachineTemplates: PillarTemplate[] = [
  {
    id: 'pom-001',
    theme: 'Volume de posts gerados em tempo real',
    hookLine: '{X} posts gerados em {Y} minutos. Sem esforço humano. Sem bloco criativo. Só sistema.',
    bodyHints: [
      'Mostrar o processo de geração em etapas',
      'Revelar o tempo de cada etapa vs manual',
      'Apresentar o output final com exemplos reais',
      'Mostrar escala possível: semanal, mensal, anual',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 7, max: 10 },
  },
  {
    id: 'pom-002',
    theme: 'Consistência de 30 dias sem falha',
    hookLine: '30 dias. 4 posts por dia. Zero falhas. Isso não é disciplina — é engenharia.',
    bodyHints: [
      'Mostrar o calendário de postagem completo do mês',
      'Revelar que nenhum post foi criado manualmente',
      'Comparar com a média do mercado em consistência',
      'Apresentar o impacto no alcance orgânico',
    ],
    variables: [],
    toneIntensity: 'high',
    slideRange: { min: 7, max: 10 },
  },
  {
    id: 'pom-003',
    theme: 'ROI documentado de automação de conteúdo',
    hookLine: 'R$ {X} investido em automação. R$ {Y} em receita gerada através do canal. Você ainda questiona o ROI?',
    bodyHints: [
      'Apresentar o custo do sistema vs retorno documentado',
      'Mostrar a rastreabilidade de cliente originado pelo conteúdo',
      'Comparar com ROI de agência ou freelancer',
      'Concluir com o número que fecha o argumento',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'pom-004',
    theme: 'Antes e depois da automação',
    hookLine: 'Antes: {X} horas por semana em conteúdo. Depois: {Y} minutos por semana. A máquina faz o resto.',
    bodyHints: [
      'Mostrar o fluxo de trabalho anterior em detalhes',
      'Mostrar o fluxo de trabalho atual com automação',
      'Quantificar o tempo liberado para o core business',
      'Apresentar o que foi feito com o tempo recuperado',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 7, max: 10 },
  },
  {
    id: 'pom-005',
    theme: 'Crescimento de alcance documentado',
    hookLine: '+{X}% de alcance orgânico em {Y} dias de uso do sistema. Dados reais. Sem impulsionamento.',
    bodyHints: [
      'Mostrar o gráfico de alcance antes e depois',
      'Identificar os fatores que contribuíram para o crescimento',
      'Comparar com a média de crescimento orgânico do segmento',
      'Apresentar o que esse alcance representa em leads/vendas',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 7, max: 10 },
  },
  {
    id: 'pom-006',
    theme: 'Custo por post: manual vs automatizado',
    hookLine: 'Post criado manualmente: R$ {X}. Post gerado pelo sistema: R$ {Y}. A matemática não mente.',
    bodyHints: [
      'Detalhar todos os custos do post manual (tempo, ferramentas, revisão)',
      'Mostrar o custo do post automatizado em detalhes',
      'Calcular a diferença em escala mensal e anual',
      'Mostrar o que a diferença pode financiar no negócio',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 7, max: 9 },
  },
  {
    id: 'pom-007',
    theme: 'Tempo economizado por mês documentado',
    hookLine: '{X} horas economizadas por mês. São {Y} dias úteis de volta pra você. O que você faria com eles?',
    bodyHints: [
      'Mostrar o cálculo detalhado de tempo por tipo de post',
      'Multiplicar por frequência semanal e mensal',
      'Converter em dias úteis para tornar tangível',
      'Apresentar o que foi feito com esse tempo: resultados',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 7, max: 10 },
  },
  {
    id: 'pom-008',
    theme: 'Qualidade constante vs variação humana',
    hookLine: 'Um humano tem dias ruins. O sistema não. {X} posts gerados com padrão de qualidade idêntico.',
    bodyHints: [
      'Mostrar a variação de qualidade em conteúdo humano ao longo do tempo',
      'Mostrar a consistência de qualidade do sistema',
      'Identificar o que "qualidade constante" significa para o algoritmo',
      'Apresentar o impacto na percepção de autoridade da marca',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 7, max: 10 },
  },
  {
    id: 'pom-009',
    theme: 'Escalabilidade da máquina de conteúdo',
    hookLine: '1 conta. Depois {X} contas. Mesma equipe. Mesmo tempo. Só aumentou o sistema.',
    bodyHints: [
      'Mostrar o modelo atual de gestão de múltiplas contas',
      'Revelar que o esforço humano não escalou junto',
      'Apresentar o que seria necessário para escalar manualmente',
      'Concluir: a máquina escala. Humanos não.',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 7, max: 10 },
  },
  {
    id: 'pom-010',
    theme: 'Resultado documentado de usuário real',
    hookLine: 'Usuário de {niche} com ShadowFeed: {X} leads gerados via conteúdo orgânico no último mês.',
    bodyHints: [
      'Apresentar o perfil do usuário (sem dados pessoais)',
      'Mostrar o processo de conteúdo implementado',
      'Apresentar os resultados documentados em métricas',
      'Concluir com o próximo passo para quem quer replicar',
    ],
    variables: ['niche', 'X'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'pom-011',
    theme: 'Volume de nicho atendido pelo sistema',
    hookLine: 'ShadowFeed operando em {X} nichos diferentes. {Y} templates únicos. Uma só plataforma.',
    bodyHints: [
      'Mostrar a diversidade de nichos que o sistema atende',
      'Apresentar exemplos de posts para nichos distintos',
      'Revelar como a personalização funciona em escala',
      'Concluir com o poder de um sistema generalista que performa como especialista',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'medium',
    slideRange: { min: 7, max: 10 },
  },
];
