import { PillarTemplate } from '../forge-shadowfeed.types.js';

export const proofSocialTemplates: PillarTemplate[] = [
  {
    id: 'ps-001',
    theme: 'Volume of posts generated in real time',
    hookLine: '{X} posts generated in {Y} minutes. No human effort. No creative block. Just system.',
    bodyHints: [
      'Show the generation process step by step',
      'Reveal the time per step vs manual creation',
      'Present the final output with real examples',
      'Show possible scale: weekly, monthly, annual',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'ps-002',
    theme: '30-day zero-failure consistency',
    hookLine: '30 days. {X} posts per day. Zero failures. This isn\'t discipline — it\'s engineering.',
    bodyHints: [
      'Show the complete monthly posting calendar',
      'Reveal that no post was manually created',
      'Compare with the market average for consistency',
      'Present the impact on organic reach',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'ps-003',
    theme: 'Documented automation ROI',
    hookLine: '${X} invested in automation. ${Y} in revenue generated through the channel. Still questioning the ROI?',
    bodyHints: [
      'Present the system cost vs documented return',
      'Show client traceability from content origin',
      'Compare with agency or freelancer ROI',
      'Conclude with the number that closes the argument',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'ps-004',
    theme: 'Before and after automation',
    hookLine: 'Before: {X} hours per week on content. After: {Y} minutes per week. The machine does the rest.',
    bodyHints: [
      'Show the previous workflow in detail',
      'Show the current workflow with automation',
      'Quantify the time freed for core business',
      'Present what was accomplished with the recovered time',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'ps-005',
    theme: 'Documented reach growth',
    hookLine: '+{X}% organic reach in {Y} days using the system. Real data. No boosting.',
    bodyHints: [
      'Show the reach graph before and after',
      'Identify the factors that contributed to growth',
      'Compare with the segment average organic growth',
      'Present what that reach represents in leads/sales',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'ps-006',
    theme: 'Cost per post: manual vs automated',
    hookLine: 'Manually created post: ${X}. System-generated post: ${Y}. Math doesn\'t lie.',
    bodyHints: [
      'Detail all manual post costs (time, tools, review)',
      'Show the automated post cost in detail',
      'Calculate the difference at monthly and annual scale',
      'Show what the savings can fund in the business',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'ps-007',
    theme: 'Behind the scenes: how the engine works',
    hookLine: 'Here\'s what happens in the {X} seconds between pressing "generate" and having a complete carousel ready to post.',
    bodyHints: [
      'Walk through the generation pipeline step by step',
      'Show template selection, theme rotation, and persona application',
      'Reveal the quality checks built into the system',
      'Present the final output that goes to the approval queue',
    ],
    variables: ['X'],
    toneIntensity: 'medium',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'ps-008',
    theme: 'Real user result documentation',
    hookLine: '{niche} professional using ShadowFeed: {X} leads generated via organic content last month.',
    bodyHints: [
      'Present the user profile (no personal data)',
      'Show the content process implemented',
      'Present documented results in metrics',
      'Conclude with the next step for those wanting to replicate',
    ],
    variables: ['niche', 'X'],
    toneIntensity: 'high',
    slideRange: { min: 6, max: 8 },
  },
];
