import { PillarTemplate } from '../forge-shadowfeed.types.js';

export const shadowSchoolTemplates: PillarTemplate[] = [
  {
    id: 'ssa-001',
    theme: 'Como o algoritmo realmente funciona',
    hookLine: 'O algoritmo do Instagram não lê o seu conteúdo. Ele lê o comportamento das pessoas em relação ao seu conteúdo. Diferença crucial.',
    bodyHints: [
      'Explicar os sinais que o algoritmo prioriza (tempo de tela, salvar, compartilhar)',
      'Desmontar o mito de que qualidade visual é o fator principal',
      'Mostrar como consistência de horário afeta distribuição',
      'Apresentar o que você pode controlar vs o que não pode',
    ],
    variables: [],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 12 },
  },
  {
    id: 'ssa-002',
    theme: 'Por que consistência supera criatividade',
    hookLine: '{X} posts medíocres publicados consistentemente superam {Y} posts excelentes publicados esporadicamente. Sempre.',
    bodyHints: [
      'Apresentar dados de crescimento de contas consistentes vs esporádicas',
      'Explicar o efeito composto da presença constante',
      'Mostrar como o algoritmo penaliza irregularidade',
      'Concluir: sistema > talento no jogo longo',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'ssa-003',
    theme: 'A anatomia de um carrossel que converte',
    hookLine: 'Um carrossel que converte tem estrutura. Não tem inspiração. Aprenda a estrutura e o resultado vira repetível.',
    bodyHints: [
      'Apresentar a estrutura slide a slide (gancho, problema, agravamento, solução, prova, CTA)',
      'Mostrar o que cada slide deve fazer pelo leitor',
      'Revelar os erros de estrutura mais comuns',
      'Concluir com um template replicável',
    ],
    variables: [],
    toneIntensity: 'medium',
    slideRange: { min: 10, max: 12 },
  },
  {
    id: 'ssa-004',
    theme: 'As primeiras palavras determinam tudo',
    hookLine: 'Você tem {X} palavras pra prender a atenção antes do "ver mais". Quantas delas você desperdiça sendo educado?',
    bodyHints: [
      'Mostrar como o feed é escaneado, não lido',
      'Apresentar padrões de gancho que funcionam no Instagram',
      'Analisar ganchos fracos vs fortes com exemplos reais',
      'Dar uma estrutura de gancho replicável em 3 formatos',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'ssa-005',
    theme: 'O sistema de pilares de conteúdo',
    hookLine: 'Parar de inventar o que postar todo dia. O sistema de pilares é o único método que funciona sem depender de inspiração.',
    bodyHints: [
      'Definir o que é um pilar de conteúdo na prática',
      'Mostrar como definir {X} pilares para qualquer nicho',
      'Apresentar como rodar os pilares em sequência sem repetição',
      'Concluir com a equação: pilares + calendário = previsibilidade',
    ],
    variables: ['X'],
    toneIntensity: 'medium',
    slideRange: { min: 8, max: 12 },
  },
  {
    id: 'ssa-006',
    theme: 'Dados sobre timing de postagem',
    hookLine: 'Postar no horário errado pode reduzir seu alcance em até {X}%. E "horário certo" muda por nicho, não por moda.',
    bodyHints: [
      'Apresentar como identificar o melhor horário para o seu público específico',
      'Mostrar as métricas que revelam horário de pico da sua audiência',
      'Destruir o mito dos horários universais de postagem',
      'Dar um método de teste de horário em 2 semanas',
    ],
    variables: ['X'],
    toneIntensity: 'medium',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'ssa-007',
    theme: 'Como criar ganchos que prendem no carrossel',
    hookLine: 'A capa do carrossel não vende o produto. Vende o próximo slide. Entender isso muda tudo.',
    bodyHints: [
      'Explicar a função de cada slide em relação ao seguinte',
      'Mostrar padrões de capa que geram alto CTR',
      'Apresentar a psicologia da curiosidade aplicada ao carrossel',
      'Dar {X} formatos de capa testados com resultados reais',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 12 },
  },
  {
    id: 'ssa-008',
    theme: 'O paradoxo da autenticidade no Instagram',
    hookLine: 'Autenticidade é percepção, não processo. Você pode ter um sistema automatizado e ainda parecer completamente autêntico.',
    bodyHints: [
      'Diferenciar voz da marca de método de produção',
      'Mostrar que audiência não quer saber como o conteúdo foi feito',
      'Apresentar como calibrar o sistema para soar com a voz certa',
      'Concluir: autenticidade é sobre o que você diz, não como você produz',
    ],
    variables: [],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'ssa-009',
    theme: 'Por que a maioria dos carrosséis falha',
    hookLine: '{X}% dos carrosséis perdem o leitor no terceiro slide. Não é porque o conteúdo é ruim. É porque a estrutura é.',
    bodyHints: [
      'Identificar os {Y} erros mais comuns que fazem o leitor largar o carrossel',
      'Mostrar como cada erro pode ser corrigido com ajuste estrutural',
      'Apresentar exemplos de antes e depois de otimização',
      'Concluir com a checklist de um carrossel que retém',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 12 },
  },
  {
    id: 'ssa-010',
    theme: 'Estrutura de post para construção de autoridade',
    hookLine: 'Autoridade no Instagram não é ego. É estrutura repetida de prova. Aprenda a estrutura e aplique sem parar.',
    bodyHints: [
      'Definir o que constrói autoridade de verdade (dados, casos, metodologia)',
      'Apresentar a estrutura do post de autoridade slide a slide',
      'Mostrar como repetição planejada cria percepção de especialista',
      'Concluir com frequência recomendada de posts de autoridade por pilar',
    ],
    variables: [],
    toneIntensity: 'medium',
    slideRange: { min: 8, max: 12 },
  },
  {
    id: 'ssa-011',
    theme: 'Hashtags: o que realmente funciona em 2025',
    hookLine: 'Hashtags não te fazem crescer mais. Te fazem crescer diferente. E {X}% dos profissionais usam errado.',
    bodyHints: [
      'Desmistificar o papel de hashtags no alcance orgânico atual',
      'Apresentar a estratégia correta de mix de hashtags por tamanho',
      'Mostrar o que substituiu hashtags como principal fator de alcance',
      'Dar um framework de seleção de hashtags por objetivo',
    ],
    variables: ['X'],
    toneIntensity: 'medium',
    slideRange: { min: 8, max: 10 },
  },
];
