import { PillarTemplate } from '../forge-shadowfeed.types.js';

export const theOfferTemplates: PillarTemplate[] = [
  {
    id: 'off-001',
    theme: 'Custo real de social media terceirizado',
    hookLine: 'Um social media custa entre R$ {X} e R$ {Y} por mês. ShadowFeed custa {price}. Faça a conta você mesmo.',
    bodyHints: [
      'Apresentar o range de preço de mercado de social media freelancer/agência',
      'Listar o que está incluso em cada opção',
      'Mostrar o que ShadowFeed entrega que eles não entregam',
      'Concluir com o CTA direto e sem rodeios',
    ],
    variables: ['X', 'Y', 'price'],
    toneIntensity: 'high',
    slideRange: { min: 5, max: 8 },
  },
  {
    id: 'off-002',
    theme: 'O que o preço compra no mercado atual',
    hookLine: '{price} por mês. O que isso compra no mercado de marketing digital hoje? Uma reunião de briefing. Com ShadowFeed, compra {X} posts.',
    bodyHints: [
      'Fazer uma comparação direta de o que se compra com o mesmo valor',
      'Listar o que o plano ShadowFeed inclui em detalhes',
      'Apresentar o custo unitário por post gerado',
      'Concluir com o que o cliente tem em 30 dias de uso',
    ],
    variables: ['price', 'X'],
    toneIntensity: 'high',
    slideRange: { min: 5, max: 8 },
  },
  {
    id: 'off-003',
    theme: 'Agência vs ShadowFeed: a comparação direta',
    hookLine: 'Agência de marketing: R$ {X}/mês, {Y} posts por semana, reuniões toda semana. ShadowFeed: {price}/mês, posts diários, zero reuniões.',
    bodyHints: [
      'Fazer comparação side-by-side objetiva',
      'Listar os pontos de fricção de trabalhar com agência',
      'Mostrar o que ShadowFeed entrega sem a fricção',
      'Apresentar o que o cliente pode fazer com o tempo e dinheiro economizados',
    ],
    variables: ['X', 'Y', 'price'],
    toneIntensity: 'max',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'off-004',
    theme: 'Ferramentas genéricas de IA vs ShadowFeed',
    hookLine: 'ChatGPT gera texto. ShadowFeed gera conteúdo para Instagram com pilares, persona, hashtags e agenda. São coisas diferentes.',
    bodyHints: [
      'Mostrar o que é necessário para ir de "texto gerado" a "post publicado"',
      'Identificar todas as etapas que ferramentas genéricas não cobrem',
      'Mostrar como ShadowFeed cobre cada etapa',
      'Concluir: ferramenta genérica é ingrediente, ShadowFeed é prato pronto',
    ],
    variables: [],
    toneIntensity: 'high',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'off-005',
    theme: 'O teste de 30 dias sem risco',
    hookLine: '{X} dias usando ShadowFeed. Se não notar diferença na consistência do seu conteúdo, você não paga. Simples assim.',
    bodyHints: [
      'Apresentar o que o cliente vai experimentar nos {X} dias',
      'Mostrar o que é esperado de resultado em 30 dias',
      'Apresentar os termos da garantia de forma clara',
      'Concluir com o CTA de início imediato',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 5, max: 7 },
  },
  {
    id: 'off-006',
    theme: 'O custo de não ter presença consistente',
    hookLine: 'Cada semana sem postar custa {X}% de alcance orgânico acumulado. Em {Y} semanas você começa do zero.',
    bodyHints: [
      'Apresentar o dado de perda de alcance por inatividade',
      'Calcular o custo em leads/vendas de {Y} semanas sem conteúdo',
      'Mostrar o que seria necessário para recuperar esse alcance',
      'Apresentar ShadowFeed como a solução preventiva',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 5, max: 8 },
  },
  {
    id: 'off-007',
    theme: 'A matemática do social media profissional',
    hookLine: 'Você precisa de {X} posts por mês para manter presença relevante no algoritmo. Sem sistema, isso custa R$ {Y} em tempo. Com ShadowFeed: {price}.',
    bodyHints: [
      'Mostrar o cálculo completo de posts necessários por frequência',
      'Calcular o custo de produção manual para essa frequência',
      'Apresentar o custo do ShadowFeed para o mesmo volume',
      'Concluir com a equação de decisão clara',
    ],
    variables: ['X', 'Y', 'price'],
    toneIntensity: 'high',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'off-008',
    theme: 'O que acontece se você não automatizar',
    hookLine: 'Em {X} meses, seus concorrentes de {niche} que automatizaram vão ter {Y}x mais presença online do que você. E vão ser preferidos.',
    bodyHints: [
      'Projetar o crescimento de quem usa sistema vs quem não usa',
      'Mostrar o efeito composto da consistência em {X} meses',
      'Apresentar o que isso significa em termos de percepção de mercado',
      'Concluir com o custo de esperar: é sempre maior do que agir agora',
    ],
    variables: ['X', 'niche', 'Y'],
    toneIntensity: 'max',
    slideRange: { min: 5, max: 8 },
  },
  {
    id: 'off-009',
    theme: 'O plano de entrada no ShadowFeed',
    hookLine: 'Como começar em {X} minutos: crie a conta, configure os {Y} pilares, e o sistema começa a gerar na mesma hora.',
    bodyHints: [
      'Mostrar o processo de onboarding passo a passo',
      'Apresentar o tempo real para estar operacional',
      'Mostrar o primeiro post gerado como resultado imediato',
      'Concluir com o CTA de início com link direto',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'medium',
    slideRange: { min: 5, max: 7 },
  },
  {
    id: 'off-010',
    theme: 'Comparação direta de planos ShadowFeed',
    hookLine: 'Starter, Micro-Op ou Booster? Depende de quantos posts por mês você precisa. Veja o breakdown completo.',
    bodyHints: [
      'Apresentar cada plano com preço e capacidade de tokens',
      'Mostrar o volume de posts correspondente por plano',
      'Identificar o perfil ideal de cliente para cada plano',
      'Concluir com recomendação e CTA',
    ],
    variables: [],
    toneIntensity: 'medium',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'off-011',
    theme: 'ShadowFeed para profissionais de {niche}',
    hookLine: 'Profissionais de {niche} precisam de presença constante sem desviar do core business. ShadowFeed foi feito exatamente pra isso.',
    bodyHints: [
      'Apresentar os desafios específicos de conteúdo do nicho',
      'Mostrar como ShadowFeed resolve cada desafio',
      'Apresentar casos ou dados do nicho específico',
      'Concluir com o CTA direcionado ao nicho',
    ],
    variables: ['niche'],
    toneIntensity: 'high',
    slideRange: { min: 5, max: 8 },
  },
  {
    id: 'off-012',
    theme: 'Tokens que não expiram: investimento real',
    hookLine: 'Tokens extras no ShadowFeed nunca expiram. Você compra quando precisa, usa quando quiser. Sem pressão de consumir.',
    bodyHints: [
      'Apresentar o modelo de tokens extras sem expiração',
      'Mostrar como isso se diferencia de outros modelos de assinatura',
      'Calcular o custo unitário de token extra vs plano mensal',
      'Concluir com o CTA para adquirir tokens extras',
    ],
    variables: [],
    toneIntensity: 'medium',
    slideRange: { min: 5, max: 7 },
  },
];
