import { PillarTemplate } from '../forge-shadowfeed.types.js';

export const theOfferTemplates: PillarTemplate[] = [
  {
    id: 'off-001',
    theme: 'Real cost of outsourced social media',
    hookLine: 'A social media manager costs between ${X} and ${Y} per month. ShadowFeed costs {price}. Do the math yourself.',
    bodyHints: [
      'Present the market price range for freelancer/agency social media',
      'List what\'s included in each option',
      'Show what ShadowFeed delivers that they don\'t',
      'Conclude with a direct, no-nonsense CTA',
    ],
    variables: ['X', 'Y', 'price'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'off-002',
    theme: 'What the price buys in today\'s market',
    hookLine: '{price} per month. What does that buy in today\'s digital marketing market? A briefing meeting. With ShadowFeed, it buys {X} posts.',
    bodyHints: [
      'Make a direct comparison of what the same amount buys',
      'List what the ShadowFeed plan includes in detail',
      'Present the unit cost per generated post',
      'Conclude with what the client gets in 30 days of use',
    ],
    variables: ['price', 'X'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'off-003',
    theme: 'Agency vs ShadowFeed: head-to-head',
    hookLine: 'Marketing agency: ${X}/month, {Y} posts per week, weekly meetings. ShadowFeed: {price}/month, daily posts, zero meetings.',
    bodyHints: [
      'Make an objective side-by-side comparison',
      'List the friction points of working with an agency',
      'Show what ShadowFeed delivers without the friction',
      'Present what the client can do with saved time and money',
    ],
    variables: ['X', 'Y', 'price'],
    toneIntensity: 'max',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'off-004',
    theme: 'Generic AI tools vs ShadowFeed',
    hookLine: 'ChatGPT generates text. ShadowFeed generates Instagram content with pillars, persona, hashtags, and scheduling. These are different things.',
    bodyHints: [
      'Show what\'s needed to go from "generated text" to "published post"',
      'Identify all the steps generic tools don\'t cover',
      'Show how ShadowFeed covers each step',
      'Conclude: generic tool is an ingredient, ShadowFeed is the finished dish',
    ],
    variables: [],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'off-005',
    theme: 'The risk-free trial',
    hookLine: '{X} days using ShadowFeed. If you don\'t notice a difference in your content consistency, you don\'t pay. Simple.',
    bodyHints: [
      'Present what the client will experience in {X} days',
      'Show the expected results in 30 days',
      'Present the guarantee terms clearly',
      'Conclude with an immediate-start CTA',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'off-006',
    theme: 'The cost of not having consistent presence',
    hookLine: 'Every week without posting costs {X}% of accumulated organic reach. In {Y} weeks you start from zero.',
    bodyHints: [
      'Present the data on reach loss from inactivity',
      'Calculate the cost in leads/sales of {Y} weeks without content',
      'Show what would be needed to recover that reach',
      'Present ShadowFeed as the preventive solution',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'off-007',
    theme: 'The professional social media math',
    hookLine: 'You need {X} posts per month to maintain relevant presence in the algorithm. Without a system, that costs ${Y} in time. With ShadowFeed: {price}.',
    bodyHints: [
      'Show the complete calculation of posts needed by frequency',
      'Calculate the manual production cost for that frequency',
      'Present the ShadowFeed cost for the same volume',
      'Conclude with a clear decision equation',
    ],
    variables: ['X', 'Y', 'price'],
    toneIntensity: 'high',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'off-008',
    theme: 'What happens if you don\'t automate',
    hookLine: 'In {X} months, your {niche} competitors who automated will have {Y}x more online presence than you. And they\'ll be preferred.',
    bodyHints: [
      'Project the growth of system users vs non-users',
      'Show the compound effect of consistency over {X} months',
      'Present what this means in terms of market perception',
      'Conclude: the cost of waiting is always higher than acting now',
    ],
    variables: ['X', 'niche', 'Y'],
    toneIntensity: 'max',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'off-009',
    theme: 'Getting started with ShadowFeed',
    hookLine: 'How to start in {X} minutes: create the account, configure your {Y} pillars, and the system starts generating immediately.',
    bodyHints: [
      'Show the onboarding process step by step',
      'Present the real time to be operational',
      'Show the first generated post as an immediate result',
      'Conclude with a start CTA with direct link',
    ],
    variables: ['X', 'Y'],
    toneIntensity: 'medium',
    slideRange: { min: 8, max: 10 },
  },
  {
    id: 'off-010',
    theme: 'ShadowFeed plan comparison',
    hookLine: 'Starter, Micro-Op, or Booster? Depends on how many posts per month you need. See the complete breakdown.',
    bodyHints: [
      'Present each plan with price and token capacity',
      'Show the corresponding post volume per plan',
      'Identify the ideal client profile for each plan',
      'Conclude with recommendation and CTA',
    ],
    variables: [],
    toneIntensity: 'medium',
    slideRange: { min: 8, max: 10 },
  },
];
