import { PillarTemplate } from '../forge-shadowfeed.types.js';

export const wakeUpSlapTemplates: PillarTemplate[] = [
  {
    id: 'wus-001',
    theme: 'Time wasted on manual content creation',
    hookLine: 'You spent {X} hours creating content this month. How much did that cost you in real money?',
    bodyHints: [
      'Calculate the hourly cost of the professional vs results generated',
      'Compare with the cost of automation',
      'Show the equation nobody does',
      'Land on the number that will sting',
    ],
    variables: ['X'],
    toneIntensity: 'max',
    slideRange: { min: 4, max: 6 },
  },
  {
    id: 'wus-002',
    theme: 'The hidden cost of manual creativity',
    hookLine: '{niche} professionals spend {X} hours per week thinking about what to post. That\'s not strategy. That\'s disguised unproductivity.',
    bodyHints: [
      'List where that time really goes (browsing, references, editing)',
      'Show the opportunity cost',
      'Compare with what a system does in minutes',
      'End with the raw reality: time is the only non-renewable resource',
    ],
    variables: ['niche', 'X'],
    toneIntensity: 'max',
    slideRange: { min: 4, max: 6 },
  },
  {
    id: 'wus-003',
    theme: 'Dependency on inspiration',
    hookLine: 'Your content strategy depends on "feeling inspired"? Then it\'s not a strategy. It\'s luck.',
    bodyHints: [
      'Define what real strategy is vs improvisation',
      'Show how top professionals treat content as a system',
      'Destroy the myth of spontaneous authenticity',
      'Present the alternative: a replicable process',
    ],
    variables: [],
    toneIntensity: 'max',
    slideRange: { min: 4, max: 6 },
  },
  {
    id: 'wus-004',
    theme: 'The manual consistency trap',
    hookLine: '{X} posts per week. That\'s what consistency requires. How many do you actually deliver?',
    bodyHints: [
      'Show the market\'s irregular posting pattern',
      'Explain what inconsistency does to the algorithm',
      'Calculate the accumulated damage to organic reach',
      'Show the problem isn\'t lack of content, it\'s lack of system',
    ],
    variables: ['X'],
    toneIntensity: 'max',
    slideRange: { min: 4, max: 6 },
  },
  {
    id: 'wus-005',
    theme: 'What your hourly rate says about manual posts',
    hookLine: 'If your hour is worth ${X}, every manually created post costs double. You\'re paying to look busy.',
    bodyHints: [
      'Do the effort/result/hour calculation',
      'Compare with hiring a freelancer',
      'Show the absurdity of the equation',
      'Present what an automated system solves',
    ],
    variables: ['X'],
    toneIntensity: 'max',
    slideRange: { min: 4, max: 6 },
  },
  {
    id: 'wus-006',
    theme: 'Your competitor already automated',
    hookLine: 'While you struggle to create one post, your {niche} competitor just generated {X} for the entire month.',
    bodyHints: [
      'Show the competitive asymmetry created by AI',
      'Illustrate what happens to those still doing it manually',
      'Show it\'s not about quality, it\'s about scale',
      'Conclude: the advantage window is closing',
    ],
    variables: ['niche', 'X'],
    toneIntensity: 'max',
    slideRange: { min: 4, max: 6 },
  },
  {
    id: 'wus-007',
    theme: 'The authentic content lie',
    hookLine: '"Authentic content" became an excuse for having no process. Authenticity doesn\'t pay bills. Consistency does.',
    bodyHints: [
      'Deconstruct the authenticity cult on Instagram',
      'Show that big creators have teams or systems',
      'Differentiate authentic voice from manual process',
      'Conclude: authenticity is tone, not production method',
    ],
    variables: [],
    toneIntensity: 'max',
    slideRange: { min: 4, max: 6 },
  },
  {
    id: 'wus-008',
    theme: 'Creating content by hand in 2026',
    hookLine: 'Still creating content by hand in 2026? That\'s like printing maps while GPS exists.',
    bodyHints: [
      'List tools that eliminated manual work in other fields',
      'Show that manual content is the last resistance driven by ego',
      'Calculate what you lost in 12 months of inefficiency',
      'Present the contrast with those who adopted automation',
    ],
    variables: [],
    toneIntensity: 'max',
    slideRange: { min: 4, max: 6 },
  },
  {
    id: 'wus-009',
    theme: 'The professional who disappears from the feed',
    hookLine: 'You vanished for {X} weeks from the feed. Know what happens to those who disappear from the algorithm? Nothing. Literally nothing.',
    bodyHints: [
      'Explain what inconsistency does to reach',
      'Show how the algorithm treats those who disappear',
      'Calculate how many followers/reach are lost',
      'Show the solution isn\'t willpower, it\'s a system',
    ],
    variables: ['X'],
    toneIntensity: 'max',
    slideRange: { min: 4, max: 6 },
  },
  {
    id: 'wus-010',
    theme: 'The monthly content plan joke',
    hookLine: 'You planned the month\'s content on Sunday. By Wednesday you abandoned the plan. Sound familiar?',
    bodyHints: [
      'List the real reasons planning fails',
      'Show that planning without a system is science fiction',
      'Differentiate editorial calendar from content machine',
      'Present what changes when the system executes for you',
    ],
    variables: [],
    toneIntensity: 'max',
    slideRange: { min: 4, max: 6 },
  },
];
