import { PillarTemplate } from '../forge-shadowfeed.types.js';

export const wakeUpSlapTemplates: PillarTemplate[] = [
  {
    id: 'wus-001',
    theme: 'Desperdício de tempo na criação manual',
    hookLine: 'Você gastou {X} horas criando conteúdo esse mês. Quanto isso te custou em dinheiro real?',
    bodyHints: [
      'Calcule o custo hora do profissional vs resultado gerado',
      'Compare com o custo de automação',
      'Mostre a equação que ninguém faz',
      'Chegue no número que vai incomodar',
    ],
    variables: ['X'],
    toneIntensity: 'max',
    slideRange: { min: 5, max: 7 },
  },
  {
    id: 'wus-002',
    theme: 'O custo oculto da criatividade manual',
    hookLine: 'Profissionais de {niche} passam {X} horas por semana pensando no que postar. Isso não é estratégia. É improdutividade disfarçada.',
    bodyHints: [
      'Listar onde esse tempo realmente vai (redes, referências, edição)',
      'Mostrar o custo de oportunidade',
      'Comparar com o que um sistema faz em minutos',
      'Encerrar com a realidade nua: tempo é o único recurso não renovável',
    ],
    variables: ['niche', 'X'],
    toneIntensity: 'max',
    slideRange: { min: 5, max: 8 },
  },
  {
    id: 'wus-003',
    theme: 'Dependência de inspiração',
    hookLine: 'Sua estratégia de conteúdo depende de "estar inspirado"? Então não é estratégia. É sorte.',
    bodyHints: [
      'Definir o que é estratégia de verdade vs improviso',
      'Mostrar como profissionais de top tratam conteúdo como sistema',
      'Destruir o mito da autenticidade espontânea',
      'Apresentar a alternativa: processo replicável',
    ],
    variables: [],
    toneIntensity: 'max',
    slideRange: { min: 5, max: 7 },
  },
  {
    id: 'wus-004',
    theme: 'A armadilha da consistência manual',
    hookLine: '{X} posts por semana. Consistência exige isso. Quantos você realmente entrega?',
    bodyHints: [
      'Mostrar o padrão de postagem irregular do mercado',
      'Explicar o que inconsistência faz com o algoritmo',
      'Calcular o dano acumulado em alcance orgânico',
      'Mostrar que o problema não é falta de conteúdo, é falta de sistema',
    ],
    variables: ['X'],
    toneIntensity: 'max',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'wus-005',
    theme: 'Quanto vale sua hora vs criar posts',
    hookLine: 'Se sua hora vale R$ {X}, cada post criado manualmente custa o dobro. Você está pagando pra parecer ocupado.',
    bodyHints: [
      'Fazer a conta de hora/esforço/resultado',
      'Comparar com contratação de freelancer',
      'Mostrar o absurdo da equação',
      'Apresentar o que um sistema automatizado resolve',
    ],
    variables: ['X'],
    toneIntensity: 'max',
    slideRange: { min: 5, max: 7 },
  },
  {
    id: 'wus-006',
    theme: 'Seu concorrente já automatizou',
    hookLine: 'Enquanto você luta pra criar um post, seu concorrente de {niche} acabou de gerar {X} para o mês inteiro.',
    bodyHints: [
      'Mostrar a assimetria competitiva que surgiu com IA',
      'Ilustrar o que acontece com quem ainda faz manual',
      'Mostrar que não é sobre qualidade, é sobre escala',
      'Concluir: a janela de vantagem está fechando',
    ],
    variables: ['niche', 'X'],
    toneIntensity: 'max',
    slideRange: { min: 5, max: 8 },
  },
  {
    id: 'wus-007',
    theme: 'A mentira do conteúdo autêntico',
    hookLine: '"Conteúdo autêntico" virou desculpa pra não ter processo. Autenticidade não paga conta. Consistência paga.',
    bodyHints: [
      'Desconstruir o culto da autenticidade no Instagram',
      'Mostrar que grandes criadores têm equipe ou sistema',
      'Diferenciar voz autêntica de processo manual',
      'Concluir: autenticidade é tom, não método de produção',
    ],
    variables: [],
    toneIntensity: 'max',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'wus-008',
    theme: 'Criar conteúdo na mão em 2025',
    hookLine: 'Ainda criando conteúdo na mão em 2025? Isso é como imprimir mapas enquanto o GPS existe.',
    bodyHints: [
      'Listar ferramentas que eliminaram trabalho manual em outras áreas',
      'Mostrar que conteúdo manual é a última resistência por ego',
      'Calcular o que você perdeu em 12 meses de ineficiência',
      'Apresentar o contraste com quem adotou automação',
    ],
    variables: [],
    toneIntensity: 'max',
    slideRange: { min: 5, max: 7 },
  },
  {
    id: 'wus-009',
    theme: 'O profissional que desaparece do feed',
    hookLine: 'Você sumiu por {X} semanas do feed. Sabe o que acontece com quem some do algoritmo? Nada. Literalmente nada.',
    bodyHints: [
      'Explicar o que inconsistência faz com o alcance',
      'Mostrar como o algoritmo trata quem some',
      'Calcular quanto seguidores/reach se perde',
      'Mostrar que a solução não é força de vontade, é sistema',
    ],
    variables: ['X'],
    toneIntensity: 'max',
    slideRange: { min: 5, max: 8 },
  },
  {
    id: 'wus-010',
    theme: 'A piada do planejamento de conteúdo mensal',
    hookLine: 'Você planejou o conteúdo do mês no domingo. Na quarta-feira abandonou o plano. Soa familiar?',
    bodyHints: [
      'Listar os motivos reais que fazem o planejamento falhar',
      'Mostrar que planejamento sem sistema é ficção científica',
      'Diferenciar calendário editorial de máquina de conteúdo',
      'Apresentar o que muda quando o sistema executa por você',
    ],
    variables: [],
    toneIntensity: 'max',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'wus-011',
    theme: 'Freelancer de social media não é solução',
    hookLine: 'Você paga R$ {X}/mês pra um freelancer de social media. Ele usa ChatGPT pra gerar o conteúdo. Você sabia disso?',
    bodyHints: [
      'Revelar o que freelancers realmente fazem nos bastidores',
      'Mostrar que você está pagando pela interface, não pela inteligência',
      'Calcular o markup que você paga por algo que pode ter direto',
      'Apresentar a alternativa de ter seu próprio sistema',
    ],
    variables: ['X'],
    toneIntensity: 'max',
    slideRange: { min: 5, max: 7 },
  },
  {
    id: 'wus-012',
    theme: 'O custo invisível da inconsistência',
    hookLine: '{X}% da percepção de autoridade de uma marca vem de consistência de presença. Não de qualidade de post individual.',
    bodyHints: [
      'Mostrar dados sobre consistência vs qualidade no Instagram',
      'Ilustrar como marcas irrelevantes dominam pelo volume',
      'Explicar por que qualidade sem frequência é invisível',
      'Concluir com a equação que importa: presença > perfeição',
    ],
    variables: ['X'],
    toneIntensity: 'high',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'wus-013',
    theme: 'A realidade do algoritmo em 2025',
    hookLine: 'O algoritmo do Instagram não recompensa qualidade. Recompensa previsibilidade. Você é previsível?',
    bodyHints: [
      'Explicar como o algoritmo aprende padrões de postagem',
      'Mostrar o que acontece quando você é imprevisível',
      'Mostrar o que acontece quando você é consistente',
      'Concluir: vencer o algoritmo não é arte, é engenharia',
    ],
    variables: [],
    toneIntensity: 'max',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'wus-014',
    theme: 'Agência de marketing vs realidade',
    hookLine: 'Você contratou uma agência por R$ {X}/mês. Eles têm {niche} como cliente. Você acha que seu conteúdo é prioridade deles?',
    bodyHints: [
      'Mostrar a realidade da capacidade de agências com múltiplos clientes',
      'Revelar o que "gestão de redes" realmente significa na prática',
      'Mostrar o conflito de incentivos estrutural',
      'Apresentar a alternativa de autonomia total',
    ],
    variables: ['X', 'niche'],
    toneIntensity: 'max',
    slideRange: { min: 5, max: 8 },
  },
  {
    id: 'wus-015',
    theme: 'O paradoxo do criador que odeia criar',
    hookLine: 'Você entrou no negócio de {niche}. Não no negócio de criar conteúdo. Por que está gastando {X}% do seu tempo com isso?',
    bodyHints: [
      'Identificar o paradoxo central: especialista virou produtor de conteúdo',
      'Mostrar o custo de oportunidade de não focar no core business',
      'Apresentar a distinção entre ter presença e produzir conteúdo',
      'Concluir: delegar conteúdo pra sistema é inteligência, não preguiça',
    ],
    variables: ['niche', 'X'],
    toneIntensity: 'high',
    slideRange: { min: 6, max: 8 },
  },
  {
    id: 'wus-016',
    theme: 'A armadilha do perfeccionismo no conteúdo',
    hookLine: 'Você não postou essa semana porque o conteúdo "não estava bom o suficiente". Seu concorrente postou {X} vezes. Imperfeitamente.',
    bodyHints: [
      'Destruir o mito do post perfeito',
      'Mostrar o custo real do perfeccionismo em alcance',
      'Apresentar dados de consistência vs qualidade',
      'Concluir: feito e publicado sempre vence perfeito e não publicado',
    ],
    variables: ['X'],
    toneIntensity: 'max',
    slideRange: { min: 5, max: 7 },
  },
];
